Report

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,90 +1,3 @@
-# name: Run Cypress Tests
-
-# on:
-#   push:
-#     branches:
-#       - master
-
-# jobs:
-#   test:
-#     runs-on: ubuntu-latest
-
-#     steps:
-#     - name: Checkout the repository
-#       uses: actions/checkout@v4
-
-#     - name: Set up Node.js
-#       uses: actions/setup-node@v4
-#       with:
-#         node-version: '18'
-
-#     - name: Install dependencies
-#       run: |
-#         npm ci
-
-#     - name: Run Cypress tests (Feature files only)
-#       run: |
-#         npx cypress run --browser chrome --headless --config video=false --env retries=2
-#       env:
-#         CYPRESS_validEmail: ${{ secrets.CYPRESS_VALID_EMAIL }}
-#         CYPRESS_validPassword: ${{ secrets.CYPRESS_VALID_PASSWORD }}
-
-#     - name: Upload screenshots on failure
-#       if: failure()
-#       uses: actions/upload-artifact@v4
-#       with:
-#         name: cypress-screenshots
-#         path: cypress/screenshots/
-
-#     - name: Display test result
-#       run: |
-#         if [ $? -eq 0 ]; then echo "Cypress tests passed"; else echo "Cypress tests failed"; exit 1; fi
-
-# name: Run Cypress Tests
-
-# on:
-#   push:
-#     branches:
-#       - master
-
-# jobs:
-#   test:
-#     runs-on: ubuntu-latest
-
-#     steps:
-#     - name: Checkout the repository
-#       uses: actions/checkout@v4
-
-#     - name: Set up Node.js
-#       uses: actions/setup-node@v4
-#       with:
-#         node-version: '18'
-
-#     - name: Install dependencies
-#       run: |
-#         npm ci
-
-#     - name: Run Cypress tests (Feature files only)
-#       run: |
-#         npx cypress run --browser chrome --headless --config video=false --env retries=2
-#       env:
-#         CYPRESS_validEmail: ${{ secrets.CYPRESS_VALID_EMAIL }}
-#         CYPRESS_validPassword: ${{ secrets.CYPRESS_VALID_PASSWORD }}
-#         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-#         SLACK_USER_ID: ${{ secrets.SLACK_USER_ID }}
-
-#     - name: Upload screenshots on failure
-#       if: failure()
-#       uses: actions/upload-artifact@v4
-#       with:
-#         name: cypress-screenshots
-#         path: cypress/screenshots/
-
-#     - name: Display test result
-#       run: |
-#         if [ $? -eq 0 ]; then echo "Cypress tests passed"; else echo "Cypress tests failed"; exit 1; fi
-
-# reporting code
 name: Run Cypress Tests
 
 on:
@@ -121,7 +34,8 @@ jobs:
     - name: Generate Allure Report
       if: always()
       run: |
-        npx allure generate allure-results --clean -o allure-report
+        npm run allure:clean
+        npm run allure:generate
       env:
         ALLURE_RESULTS_DIR: allure-results
 
@@ -139,7 +53,14 @@ jobs:
       with:
         name: cypress-screenshots
         path: cypress/screenshots/
+        retention-days: 7
 
     - name: Display test result
+      if: always()
       run: |
-        if [ $? -eq 0 ]; then echo "Cypress tests passed"; else echo "Cypress tests failed"; exit 1; fi
+        if [ ${{ job.status }} == "success" ]; then
+          echo "Cypress tests passed"
+        else
+          echo "Cypress tests failed"
+          exit 1
+        fi
